name = "remix"
roles = ["frontend", "backend"]
webhooks_path = "https://example.com/webhooks/app/uninstalled"

[commands]
predev = "npx prisma generate"
dev = "npx prisma migrate deploy && npm exec remix vite:dev"
